id: P001823
initial_creation_type: ocr
source_metadata:
  id: bdr:W23893
  title: གསུང་འབུམ། ཚོགས་དྲུག་རང་གྲོལ
  author: ''
  volumes:
    fe6b7c70c6494263859e14298048d9f6:
      image_group_id: I3145
      title: ''
      volume_number: 1
      total_pages: 1062
    d671a690df044a9fae5f9cc7a31481e3:
      image_group_id: I3146
      title: ''
      volume_number: 2
      total_pages: 946
    666f4b2d7cac439e999ed258b269b800:
      image_group_id: I3147
      title: ''
      volume_number: 3
      total_pages: 776
    7fc6830aa5ca465494b9560a98d4757f:
      image_group_id: I3148
      title: ''
      volume_number: 4
      total_pages: 624
    272a9f2e920a4e018db7e1f3c89209d9:
      image_group_id: I3149
      title: ''
      volume_number: 5
      total_pages: 572
    6f09f9a2cce0446095afda79a19114f6:
      image_group_id: I3150
      title: ''
      volume_number: 6
      total_pages: 756
    4fac2357a98b4c2d8c71bde1f9847a02:
      image_group_id: I3151
      title: ''
      volume_number: 7
      total_pages: 658
    5e043166670f48429c9ecd996740109b:
      image_group_id: I3152
      title: ''
      volume_number: 8
      total_pages: 536
    0f29eab776fb46e395cf22c7ce0e0a20:
      image_group_id: I3153
      title: ''
      volume_number: 9
      total_pages: 596
    a517b038301a40d0b8d6ef6962405b62:
      image_group_id: I3154
      title: ''
      volume_number: 10
      total_pages: 668
    6df3c3adbd7c4aa48b20cf0b2b8f5116:
      image_group_id: I3155
      title: ''
      volume_number: 11
      total_pages: 648
    381048514d674b1db88ec134ec76003a:
      image_group_id: I3156
      title: ''
      volume_number: 12
      total_pages: 630
    66bbb03f8b7849438dc5efed76330390:
      image_group_id: I3157
      title: ''
      volume_number: 13
      total_pages: 702
    18c82ba87b5742b0b200530381bf314c:
      image_group_id: I3158
      title: ''
      volume_number: 14
      total_pages: 884
