id: IE55EC9AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:38:05+00:00'
last_modified: '2022-06-07T15:16:44.828341+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23893
  title: གསུང་འབུམ། ཚོགས་དྲུག་རང་གྲོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2BB3:
      image_group_id: I3145
      title: ''
      total_pages: 1062
      order: 1
      base_file: 2BB3.txt
    B505:
      image_group_id: I3146
      title: ''
      total_pages: 946
      order: 2
      base_file: B505.txt
    1EB9:
      image_group_id: I3147
      title: ''
      total_pages: 776
      order: 3
      base_file: 1EB9.txt
    '2570':
      image_group_id: I3148
      title: ''
      total_pages: 624
      order: 4
      base_file: 2570.txt
    '5992':
      image_group_id: I3149
      title: ''
      total_pages: 572
      order: 5
      base_file: 5992.txt
    EE19:
      image_group_id: I3150
      title: ''
      total_pages: 756
      order: 6
      base_file: EE19.txt
    2B73:
      image_group_id: I3151
      title: ''
      total_pages: 658
      order: 7
      base_file: 2B73.txt
    63E6:
      image_group_id: I3152
      title: ''
      total_pages: 536
      order: 8
      base_file: 63E6.txt
    D40C:
      image_group_id: I3153
      title: ''
      total_pages: 596
      order: 9
      base_file: D40C.txt
    0BEA:
      image_group_id: I3154
      title: ''
      total_pages: 668
      order: 10
      base_file: 0BEA.txt
    1C50:
      image_group_id: I3155
      title: ''
      total_pages: 648
      order: 11
      base_file: 1C50.txt
    0698:
      image_group_id: I3156
      title: ''
      total_pages: 630
      order: 12
      base_file: 0698.txt
    '3884':
      image_group_id: I3157
      title: ''
      total_pages: 702
      order: 13
      base_file: 3884.txt
    650F:
      image_group_id: I3158
      title: ''
      total_pages: 884
      order: 14
      base_file: 650F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
