id: IE55EC9AF
legacy_id: P001823
ocr_import_info:
  bdrc_scan_id: W23893
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T17:30:31'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:56:06.440901+00:00'
last_modified: 2022-09-02 13:00:46.547370
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23893
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23893
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཚོགས་དྲུག་རང་གྲོལ།
  author: ཞབས་དཀར་བ་ཚོགས་དྲུག་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.8580244160873802
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3148:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3148
      total_pages: 624
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3148.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9514952960006797
    legacy_id: v004
  I3158:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3158
      total_pages: 884
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I3158.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9315934086342232
    legacy_id: v014
  I3146:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3146
      total_pages: 946
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3146.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7545289074585133
    legacy_id: v002
  I3147:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3147
      total_pages: 776
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3147.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7122292432317179
    legacy_id: v003
  I3151:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3151
      total_pages: 658
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3151.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9401569051587151
    legacy_id: v007
  I3152:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3152
      total_pages: 536
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3152.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9467148393331493
    legacy_id: v008
  I3149:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3149
      total_pages: 572
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3149.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9481891133959242
    legacy_id: v005
  I3157:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3157
      total_pages: 702
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I3157.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9427340246150677
    legacy_id: v013
  I3153:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3153
      total_pages: 596
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3153.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9426545319562227
    legacy_id: v009
  I3150:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3150
      total_pages: 756
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3150.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.940329803469398
    legacy_id: v006
  I3155:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3155
      total_pages: 648
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3155.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9417108870742996
    legacy_id: v011
  I3156:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3156
      total_pages: 630
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3156.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9381180454798309
    legacy_id: v012
  I3154:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3154
      total_pages: 668
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3154.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9363076241313679
    legacy_id: v010
  I3145:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3145
      total_pages: 1062
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3145.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6910273850438144
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
